-- Create database
CREATE DATABASE OPENROUTESERVICE_SETUP;

-- Create internal stages
CREATE STAGE OPENROUTESERVICE_SETUP.PUBLIC.ORS_SPCS_STAGE ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' ) DIRECTORY=(ENABLE=TRUE);
CREATE STAGE OPENROUTESERVICE_SETUP.PUBLIC.ORS_GRAPHS_SPCS_STAGE ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' ) DIRECTORY=(ENABLE=TRUE);
CREATE STAGE OPENROUTESERVICE_SETUP.PUBLIC.ORS_ELEVATION_CACHE_SPCS_STAGE ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' ) DIRECTORY=(ENABLE=TRUE);

-- Create image repository
CREATE IMAGE REPOSITORY OPENROUTESERVICE_SETUP_EUROPE.PUBLIC.IMAGE_REPOSITORY;

DROP IMAGE REPOSITORY OPENROUTESERVICE_SETUP_EUROPE.PUBLIC.IMAGE_REPOSITORY;


alter stage OPENROUTESERVICE_SETUP_europe.PUBLIC.ORS_SPCS_STAGE refresh;